### ISSUE TITLE
Got a lot of warning and error during installation

### ISSUE THREAD

**Issue by PDXIII** [chrisfsampaio/imsg#30]
Hi Chris!

I’d really like to try your imsg, but ran in a lot of trouble while installing it. So, I let it be ;-(
Maybe the out put helps you to improve your software.

Greetz,
P

System:
Macbook Pro 
OS X Mavericks
Ruby 2.0.0p247

```
Building native extensions.  This could take a while...
ERROR:  Error installing imsg:
    ERROR: Failed to build gem native extension.

    /Users/PDXIII/.rvm/rubies/ruby-2.0.0-p247/bin/ruby extconf.rb
extconf.rb:44:in `<main>': Use RbConfig instead of obsolete and deprecated Config.
extconf.rb:44:in `<main>': Use RbConfig instead of obsolete and deprecated Config.
create /Users/PDXIII/.rvm/gems/ruby-2.0.0-p247/gems/rb-appscript-0.6.1/src/osx_ruby.h ...
create /Users/PDXIII/.rvm/gems/ruby-2.0.0-p247/gems/rb-appscript-0.6.1/src/osx_intern.h ...
creating Makefile

make "DESTDIR="
compiling src/rbae.c
src/rbae.c:501:8: warning: 'FSRefMakePath' is deprecated: first deprecated in OS X 10.8 [-Wdeprecated-declarations]
        err = FSRefMakePath(&outAppRef, path, PATH_MAX);
              ^
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Files.h:4086:18: note: 'FSRefMakePath' declared here
extern OSStatus  FSRefMakePath(const FSRef *ref, UInt8 *path, UInt32 pathBufferSize)     __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_8, __IPHONE_NA, __IPHONE_NA);
                 ^
src/rbae.c:514:8: warning: 'FSPathMakeRef' is deprecated: first deprecated in OS X 10.8 [-Wdeprecated-declarations]
        err = FSPathMakeRef((UInt8 *)StringValuePtr(path), &appRef, NULL);
              ^
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Files.h:4115:18: note: 'FSPathMakeRef' declared here
extern OSStatus  FSPathMakeRef(const UInt8 *path, FSRef *ref, Boolean *isDirectory)        __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_8, __IPHONE_NA, __IPHONE_NA);
                 ^
src/rbae.c:517:9: warning: 'GetNextProcess' is deprecated: first deprecated in OS X 10.9 [-Wdeprecated-declarations]
                err = GetNextProcess(&psn);
                      ^
/System/Library/Frameworks/ApplicationServices.framework/Frameworks/HIServices.framework/Headers/Processes.h:452:1: note: 'GetNextProcess' declared here
GetNextProcess(ProcessSerialNumber * PSN)                     AVAILABLE_MAC_OS_X_VERSION_10_0_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_9;
^
src/rbae.c:519:9: warning: 'GetProcessBundleLocation' is deprecated: first deprecated in OS X 10.9 [-Wdeprecated-declarations]
                err = GetProcessBundleLocation(&psn, &foundRef);
                      ^
/System/Library/Frameworks/ApplicationServices.framework/Frameworks/HIServices.framework/Headers/Processes.h:815:1: note: 'GetProcessBundleLocation' declared here
GetProcessBundleLocation(
^
src/rbae.c:521:7: warning: 'FSCompareFSRefs' is deprecated: first deprecated in OS X 10.8 [-Wdeprecated-declarations]
                if (FSCompareFSRefs(&appRef, &foundRef) == noErr)
                    ^
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Files.h:1850:15: note: 'FSCompareFSRefs' declared here
extern OSErr  FSCompareFSRefs(const FSRef *ref1, const FSRef *ref2)                     __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_8, __IPHONE_NA, __IPHONE_NA);
              ^
src/rbae.c:533:8: warning: 'GetProcessForPID' is deprecated: first deprecated in OS X 10.9 [-Wdeprecated-declarations]
        err = GetProcessForPID(NUM2INT(pid), &psn);
              ^
/System/Library/Frameworks/ApplicationServices.framework/Frameworks/HIServices.framework/Headers/Processes.h:930:1: note: 'GetProcessForPID' declared here
GetProcessForPID(
^
src/rbae.c:546:8: warning: 'FSPathMakeRef' is deprecated: first deprecated in OS X 10.8 [-Wdeprecated-declarations]
        err = FSPathMakeRef((UInt8 *)StringValuePtr(path), &appRef, NULL);
              ^
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Files.h:4115:18: note: 'FSPathMakeRef' declared here
extern OSStatus  FSPathMakeRef(const UInt8 *path, FSRef *ref, Boolean *isDirectory)        __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_8, __IPHONE_NA, __IPHONE_NA);
                 ^
src/rbae.c:709:8: warning: 'FSPathMakeRef' is deprecated: first deprecated in OS X 10.8 [-Wdeprecated-declarations]
        err = FSPathMakeRef((UInt8 *)StringValuePtr(path), &fsRef, NULL);
              ^
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Files.h:4115:18: note: 'FSPathMakeRef' declared here
extern OSStatus  FSPathMakeRef(const UInt8 *path, FSRef *ref, Boolean *isDirectory)        __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_8, __IPHONE_NA, __IPHONE_NA);
                 ^
8 warnings generated.
compiling src/SendThreadSafe.c
src/SendThreadSafe.c:362:15: warning: use of logical '&&' with constant operand [-Wconstant-logical-operand]
        if (sendMode && kAEWaitReply) {
                     ^  ~~~~~~~~~~~~
src/SendThreadSafe.c:362:15: note: use '&' for a bitwise operation
        if (sendMode && kAEWaitReply) {
                     ^~
                     &
src/SendThreadSafe.c:362:15: note: remove constant to silence this warning
        if (sendMode && kAEWaitReply) {
                    ~^~~~~~~~~~~~~~~
1 warning generated.
linking shared-object ae.bundle
ld: warning: directory not found for option '-L/Users/mpapis/.sm/pkg/active/lib'
ld: framework not found Carbon
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ae.bundle] Error 1


Gem files will remain installed in /Users/PDXIII/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/gems/2.0.0/gems/rb-appscript-0.6.1 for inspection.
Results logged to /Users/PDXIII/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/gems/2.0.0/gems/rb-appscript-0.6.1/./gem_make.out
```

**Comment by besi** [comment]
Similar problems here.


    $ ruby -v
    ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]

When I try to install the gem I get this:

    gem install imsg
    Building native extensions.  This could take a while...
    ERROR:  Error installing imsg:
    	ERROR: Failed to build gem native extension.
    
        /usr/local/var/rbenv/versions/2.1.2/bin/ruby extconf.rb
    extconf.rb:44:in `<main>': Use RbConfig instead of obsolete and deprecated Config.
    extconf.rb:44:in `<main>': Use RbConfig instead of obsolete and deprecated Config.
    create /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rb-appscript-0.6.1/src/osx_ruby.h ...
    create /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rb-appscript-0.6.1/src/osx_intern.h ...
    creating Makefile
    
    make "DESTDIR=" clean
    
    make "DESTDIR="
    compiling src/rbae.c
    couldn't understand kern.osversion `14.3.0'
    In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:55,
                     from /System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:20,
                     from src/rbae.c:13:
    /System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:262: error: expected ‘,’ or ‘}’ before ‘__attribute__’
    /System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414: error: expected ‘,’ or ‘}’ before ‘__attribute__’
    make: *** [rbae.o] Error 1
    
    make failed, exit code 2
    
    Gem files will remain installed in /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rb-appscript-0.6.1 for inspection.
    Results logged to /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-13/2.1.0-static/rb-appscript-0.6.1/gem_make.out

**Comment by chrisfsampaio** [comment]
Which version of **gcc** are you using?

There are [some people](https://github.com/joyent/node/issues/9182) that had the same issue and it seems to be related to **gcc**.

My `gcc --version` output:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```

**Comment by besi** [comment]
```
$ gcc --version 

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```
